/**
 * Static ad env snapshot.
 *
 * CRITICAL: Next.js only inlines `NEXT_PUBLIC_*` vars into the client bundle
 * when accessed as a *literal* member expression (`process.env.NEXT_PUBLIC_X`).
 * Dynamic lookups (`process.env[key]`) and aliasing (`const e = process.env`)
 * are NOT inlined and read as `undefined` in the browser.
 * (See node_modules/next/dist/docs/01-app/02-guides/environment-variables.md.)
 *
 * So every public ad var is read literally here, once, into a plain object.
 * Providers then index this runtime object freely — that dynamic access is
 * fine because AD_ENV is already a concrete value, not `process.env`.
 */

export type AdEnv = Record<string, string | undefined>;

export const AD_ENV: AdEnv = {
  // Global selectors
  NEXT_PUBLIC_AD_PRIMARY: process.env.NEXT_PUBLIC_AD_PRIMARY,
  NEXT_PUBLIC_AD_REQUIRE_CONSENT: process.env.NEXT_PUBLIC_AD_REQUIRE_CONSENT,

  // Google AdSense
  NEXT_PUBLIC_ADSENSE_CLIENT: process.env.NEXT_PUBLIC_ADSENSE_CLIENT,
  NEXT_PUBLIC_ADSENSE_SLOT_BANNER: process.env.NEXT_PUBLIC_ADSENSE_SLOT_BANNER,
  NEXT_PUBLIC_ADSENSE_SLOT_INLINE: process.env.NEXT_PUBLIC_ADSENSE_SLOT_INLINE,
  NEXT_PUBLIC_ADSENSE_SLOT_SIDEBAR: process.env.NEXT_PUBLIC_ADSENSE_SLOT_SIDEBAR,
  NEXT_PUBLIC_ADSENSE_SLOT_FOOTER: process.env.NEXT_PUBLIC_ADSENSE_SLOT_FOOTER,
  NEXT_PUBLIC_ADSENSE_SLOT_STICKY: process.env.NEXT_PUBLIC_ADSENSE_SLOT_STICKY,

  // Google Ad Manager (GPT)
  NEXT_PUBLIC_GAM_NETWORK_CODE: process.env.NEXT_PUBLIC_GAM_NETWORK_CODE,

  // Ezoic
  NEXT_PUBLIC_EZOIC_ENABLED: process.env.NEXT_PUBLIC_EZOIC_ENABLED,
  NEXT_PUBLIC_EZOIC_PH_BANNER: process.env.NEXT_PUBLIC_EZOIC_PH_BANNER,
  NEXT_PUBLIC_EZOIC_PH_INLINE: process.env.NEXT_PUBLIC_EZOIC_PH_INLINE,
  NEXT_PUBLIC_EZOIC_PH_SIDEBAR: process.env.NEXT_PUBLIC_EZOIC_PH_SIDEBAR,
  NEXT_PUBLIC_EZOIC_PH_FOOTER: process.env.NEXT_PUBLIC_EZOIC_PH_FOOTER,
  NEXT_PUBLIC_EZOIC_PH_STICKY: process.env.NEXT_PUBLIC_EZOIC_PH_STICKY,

  // Mediavine
  NEXT_PUBLIC_MEDIAVINE_SITE_ID: process.env.NEXT_PUBLIC_MEDIAVINE_SITE_ID,

  // Raptive (AdThrive)
  NEXT_PUBLIC_RAPTIVE_SITE_ID: process.env.NEXT_PUBLIC_RAPTIVE_SITE_ID,

  // Monumetric
  NEXT_PUBLIC_MONUMETRIC_SITE_ID: process.env.NEXT_PUBLIC_MONUMETRIC_SITE_ID,
  NEXT_PUBLIC_MONUMETRIC_PROPERTY: process.env.NEXT_PUBLIC_MONUMETRIC_PROPERTY,

  // Prebid.js header bidding
  NEXT_PUBLIC_PREBID_ENABLED: process.env.NEXT_PUBLIC_PREBID_ENABLED,
  NEXT_PUBLIC_PREBID_IX_SITE_ID: process.env.NEXT_PUBLIC_PREBID_IX_SITE_ID,
  NEXT_PUBLIC_PREBID_OPENX_UNIT: process.env.NEXT_PUBLIC_PREBID_OPENX_UNIT,
  NEXT_PUBLIC_PREBID_OPENX_DELDOMAIN: process.env.NEXT_PUBLIC_PREBID_OPENX_DELDOMAIN,
  NEXT_PUBLIC_PREBID_PUBMATIC_PUBID: process.env.NEXT_PUBLIC_PREBID_PUBMATIC_PUBID,
  NEXT_PUBLIC_PREBID_PUBMATIC_ADSLOT: process.env.NEXT_PUBLIC_PREBID_PUBMATIC_ADSLOT,
  NEXT_PUBLIC_PREBID_CRITEO_NETWORK: process.env.NEXT_PUBLIC_PREBID_CRITEO_NETWORK,
  NEXT_PUBLIC_PREBID_SOVRN_TAGID: process.env.NEXT_PUBLIC_PREBID_SOVRN_TAGID,

  // Amazon Publisher Services (TAM)
  NEXT_PUBLIC_AMAZON_TAM_PUB_ID: process.env.NEXT_PUBLIC_AMAZON_TAM_PUB_ID,

  // Media.net
  NEXT_PUBLIC_MEDIANET_CID: process.env.NEXT_PUBLIC_MEDIANET_CID,
  NEXT_PUBLIC_MEDIANET_CRID_BANNER: process.env.NEXT_PUBLIC_MEDIANET_CRID_BANNER,
  NEXT_PUBLIC_MEDIANET_CRID_INLINE: process.env.NEXT_PUBLIC_MEDIANET_CRID_INLINE,
  NEXT_PUBLIC_MEDIANET_CRID_SIDEBAR: process.env.NEXT_PUBLIC_MEDIANET_CRID_SIDEBAR,
  NEXT_PUBLIC_MEDIANET_CRID_FOOTER: process.env.NEXT_PUBLIC_MEDIANET_CRID_FOOTER,
  NEXT_PUBLIC_MEDIANET_CRID_STICKY: process.env.NEXT_PUBLIC_MEDIANET_CRID_STICKY,

  // Taboola
  NEXT_PUBLIC_TABOOLA_PUBLISHER: process.env.NEXT_PUBLIC_TABOOLA_PUBLISHER,

  // Outbrain
  NEXT_PUBLIC_OUTBRAIN_ENABLED: process.env.NEXT_PUBLIC_OUTBRAIN_ENABLED,
  NEXT_PUBLIC_OUTBRAIN_WIDGET_INLINE: process.env.NEXT_PUBLIC_OUTBRAIN_WIDGET_INLINE,
  NEXT_PUBLIC_OUTBRAIN_WIDGET_FOOTER: process.env.NEXT_PUBLIC_OUTBRAIN_WIDGET_FOOTER,

  // Carbon Ads
  NEXT_PUBLIC_CARBON_SERVE: process.env.NEXT_PUBLIC_CARBON_SERVE,
  NEXT_PUBLIC_CARBON_PLACEMENT: process.env.NEXT_PUBLIC_CARBON_PLACEMENT,

  // BuySellAds
  NEXT_PUBLIC_BSA_ENABLED: process.env.NEXT_PUBLIC_BSA_ENABLED,
  NEXT_PUBLIC_BSA_ZONE_SIDEBAR: process.env.NEXT_PUBLIC_BSA_ZONE_SIDEBAR,
  NEXT_PUBLIC_BSA_ZONE_INLINE: process.env.NEXT_PUBLIC_BSA_ZONE_INLINE,
};
