export const EVENTS = {
  FEED_LOADED:                   "feed_loaded",
  FEED_RESHUFFLED:               "feed_reshuffled",
  MOVIE_DETAIL_OPENED:           "movie_detail_opened",
  MOVIE_RATED:                   "movie_rated",
  WATCHLIST_TOGGLED:             "watchlist_toggled",
  MOVIE_DISMISSED:               "movie_dismissed",
  MOVIE_WATCHED:                 "movie_watched",
  MOOD_FILTER_APPLIED:           "mood_filter_applied",
  SEARCH_USED:                   "search_used",
  ONBOARDING_COMPLETE:           "onboarding_complete",
  PLATFORM_CHANGED:              "platform_changed",
  IMPORT_COMPLETED:              "import_completed",
  UPGRADE_PROMPT_VIEWED:         "upgrade_prompt_viewed",
  UPGRADE_CTA_CLICKED:           "upgrade_cta_clicked",
  SIGN_OUT:                      "sign_out",
  COMMUNITY_LINK_SUBMITTED:      "community_link_submitted",
  PLATFORM_SUGGESTION_SUBMITTED: "platform_suggestion_submitted",
  SHARE_USED:                    "share_used",
  TASTE_PROFILE_GENERATED:       "taste_profile_generated",
} as const;
